export 'package:flutter_application_2/presentacion/widgets/botons/boton_continuar_wiget.dart';
export 'package:flutter_application_2/presentacion/widgets/texts/titulo_text_widget.dart';
export 'package:flutter_application_2/presentacion/widgets/botons/boton_icono_widget.dart';
export 'package:flutter_application_2/presentacion/widgets/appBars/app_bar_logo_oscus_widget.dart';
export 'package:flutter_application_2/presentacion/widgets/autenticacion/registrarse_widget.dart';
export 'package:flutter_application_2/presentacion/screens/screens.dart';
export 'package:flutter_application_2/presentacion/widgets/texts/text_widget.dart';
export 'package:flutter_application_2/presentacion/widgets/botons/boton_widget.dart';
export 'package:flutter_application_2/presentacion/widgets/autenticacion/custom_scaffold.dart';
